# Site settings
title: Luco's Lab
header-img: img/home-bg.jpg
email:  eq-deluco@igh.cnrs.fr
copyright_name: Reini Luco Lab @t IGH
description: "News from the Luco's Lab at IGH (Institute of Human Genetics - France)"
baseurl: "/LucoLab"
github_username:  LucoLab

email_username:  eq-deluco@igh.cnrs.fr

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
